Android/shared/src/main/java/com/redbadger/rmm/shared_types/Msg.java, shared/src/lib.rs, shared_types/generated/com/redbadger/rmm/shared_types/Msg.java, shared_types/generated/shared_types.swift
Now that we are using `serde` to serialize over the boundary, messages can have tuple variants where appropriate, which means they can also be used directly as continuation callbacks. 
e.g. this
```rust
cmd.http.get(FACT_API_URL.to_owned(), Msg::SetFact),
```
rather than this:
```rust
cmd.http.get(FACT_API_URL.to_owned(), |bytes| Msg::SetFact { bytes }),
```
=> tuple variants

examples/cat_facts/web-nextjs/next.config.js
Right now the cat facts example is showing a runtime error when we start the repo locally:
The reason why is that Nextjs implements a Same Origin Policy by default and so our attempt to return an image from aws.random.cat/meow is met with a 503. 
This PR adds a basic cors policy as part of our nextjs config to remove this error.
=> Add basic cors policy to nextjs example repo

examples/cat_facts/README.md, rust-toolchain.toml
This seems to be needed for the iOS simulator on intel macs.
=> Add `x86_64-apple-ios` to targets list

crux_core/src/lib.rs
Noticed these sitting undocumented in the 0.2 docs.  At one point I thought these might be public API, but we've ended up hiding them sufficiently.  So rather than documenting them, lets just hide them from users.
=> Make `channels` & `executor` private.

.config/nextest.toml, .github/workflows/build.yaml, .github/workflows/rustdoc.yaml, examples/cat_facts/.config/nextest.toml
- Added a workflow that:
1. Builds & tests crux itself
2. Builds the rust code of each of the examples.
- Added a doc action that'll publish master to github docs.
Currently this doesn't build the shell side of any of the examples, that'll need to be done in a future PR.
=> Add some basic github actions

crux_macros/src/effect.rs
`split_event_type` was always looking for generic arguments in the first section of paths.  This isn't correct and meant if you provided a capability like `crux_http::Http<Event>` it'd look for generic arguments in `crux_http`, fail to find them and then complain that "all fields should be generic over the same event type"
=> Fix path support in crux_derive::Effect.

crux_core/src/capability.rs, crux_core/src/channels.rs, crux_core/src/future.rs, crux_core/src/lib.rs, crux_core/src/steps.rs, crux_core/src/stream.rs
This PR contains a first pass of the shell->core streaming mechanism for capabilities.  The API that's exposed is broadly similar to what we have now, except:
1. The capability calls `stream_from_shell` instead.
2. They get a `futures::Stream` instead of a `Future`
The shell side should be similar: they get a request with a UUID, and should send any responses to that UUID.
When the capability task ends it'll drop the underlying channel which should free up most of the core-side resources involved.  An entry will remain in the `StepRegistry`, which is not ideal but it shouldn't occupy much memory.  If another message comes in for this UUID it'll be cleaned out of the StepRegistry as well.
Stuff we'll probably need to do on top of this:
1. Actually use it somewhere, it's all theoretical …
=> Allow capabilities to stream data from the shell.

.github/workflows/pages.yaml
Publish the book in the root of the GitHub pages and the API docs in a subfolder,
so that the landing page is not a 404
=> Publish book in the root of github pages

Cargo.lock, crux_core/src/steps.rs, crux_http/Cargo.toml, crux_macros/Cargo.toml, examples/cat_facts/Cargo.lock, examples/cat_facts/cli/Cargo.toml, examples/cat_facts/shared/src/app.rs, examples/cat_facts/web-yew/Cargo.toml, examples/counter/Cargo.lock, examples/counter/cli/Cargo.toml, examples/counter/server/Cargo.toml, examples/counter/shared/src/app/mod.rs, examples/counter/web-nextjs/pnpm-lock.yaml, examples/counter/web-yew/Cargo.toml, examples/counter/web-yew/src/main.rs, examples/hello_world/Cargo.lock
This is a workaround for a bug that affects clients that compile the shared library into their binary (e.g. the Yew examples).
The Events that are sent by the shell need to be ahead of any that are marked `#[serde(skip)]` otherwise the serialization won't round-trip.
This does not affect clients that use the static library (iOS), dynamic library (Android), or Wasm (e.g. NextJS), only those that compile and link a Rust library directly (e.g. Yew).
We should, at some point, provide an API for these clients so that they can skip the serialization completely.
=> Re-order Event variants to prevent serialization errors

Cargo.lock, crux_core/Cargo.toml, crux_core/tests/capability_runtime.rs
This is part useful, part exercise in understanding what's possible with the capability runtime.
The test creates a capability which implements a hypothetical tree crawler, which needs to fetch items over the network using the Shell. In order not to open too many connections, it does it on a worker pool.
This checks that more complex scenarios like this are possible, and also allows us to potentially mess with the runtime and understand whether we introduced subtle bugs.
=> Add integration test exercising the capability async runtime

examples/counter/Cargo.lock, examples/counter/cli/Cargo.toml, examples/counter/cli/src/main.rs
I've attempted to improve the way the CLI detects whether the work is done or whether there are still some side-effects pending. This works, but I don't particularly love the solution. I'll have a go at a slitghtly different design in a separate PR, but I think this is good to go.
I also took any counter specific bits out of the implementation of the side-effects (http and sse), so they are theoretically reusable. `futures::stream::try_unfold` is pretty awesome.
=> Improve termination detection in the counter CLI

.github/workflows/pages.yaml, docs/book.toml, docs/mdbook-admonish.css, docs/src/getting_started/android.md, docs/src/getting_started/core.md, docs/src/getting_started/ios.md, docs/src/getting_started/web_react.md, docs/src/getting_started/web_yew.md, docs/src/guide/capability_apis.md, docs/src/guide/composing.md, docs/src/guide/message_interface.md, docs/src/internals/continuations.md, docs/src/internals/core_api.md, docs/src/internals/serialization.md, docs/src/internals/typegen.md, docs/src/internals/uniffi.md, docs/src/overview.md
This PR uses the [mdbook-admonish](https://github.com/tommilligan/mdbook-admonish) preprocessor to render material 3 admonitions.
For example 
To test, pull the branch and `cd docs && mdbook serve --open`
=> Adds callout blocks to docs

examples/notes/Cargo.lock, examples/notes/ios/Notes/ContentView.swift, examples/notes/shared/Cargo.toml, examples/notes/shared/src/app.rs, examples/notes/shared/src/app/note.rs, examples/notes/shared/src/capabilities.rs, examples/notes/shared/src/lib.rs, examples/notes/shared_types/build.rs, examples/notes/shared_types/generated/swift/shared_types.swift
Instead of storing the plain text of the note, it is now stored in an [Automerge](https://automerge.org/) document,
using [automerge-rs](https://github.com/automerge/automerge-rs). 
I've also added a really basic pubsub capability to be able to do an integration test for the sync. I'll go on to add
a lot more of those tests and make sure the syncing works properly.
This revealed one really nifty thing about Crux - testing the sync is just a unit test with two instances of the app
running and the test acting as the shell and exchanging messages between them. Blew my tiny mind!
=> Swap underlying store for Automerge to support sync

examples/notes/shared/src/app.rs, examples/notes/shared/src/app/note.rs
As much as I dislike refactoring in tests, this felt helpful to make the tests more readable. Not sure if there's anything in this that is worth bringing into the AppTester, maybe? Probably needs more tests of this nature to spot common patterns.
=> Add test helpers to make sync tests more straightforward

examples/notes/shared/src/app.rs, examples/notes/shared/src/app/note.rs, examples/notes/web-nextjs/src/components/Textarea/Textarea.tsx, examples/notes/web-nextjs/src/pages/index.tsx
Handle unicode characters properly in the core and in the Web UI
Automerge edits operate on the level of unicode characters (above bytes,
below grapheme clusters). The browser UI works on a byte level.
This introduces a fix for the core to operate on characters, and the React
UI to convert between the native byte offsets  and unicode offsets.
The method I currently use for this is not ideal and introduces a somewhat
noticeable lag on editing long documents with emojis in them, but I'm fairly
confident we can improve this by moving the logic into the core and exposing
both types of offsets to the shells.
=> Handle unicode characters properly in the core and in the Web UI

crux_http/src/client.rs, crux_http/src/protocol.rs, crux_http/tests/with_shell.rs, crux_http/tests/with_tester.rs, examples/cat_facts/Android/shared/src/main/java/com/redbadger/catfacts/shared_types/HttpHeader.java, examples/cat_facts/Android/shared/src/main/java/com/redbadger/catfacts/shared_types/HttpRequest.java, examples/cat_facts/Android/shared/src/main/java/com/redbadger/catfacts/shared_types/TraitHelpers.java, examples/cat_facts/shared/src/app.rs, examples/counter/Android/app/src/main/java/com/example/counter/MainActivity.kt, examples/counter/Android/app/src/main/java/com/example/counter/http.kt, examples/counter/Android/shared/src/main/java/com/example/counter/shared_types/HttpHeader.java, examples/counter/Android/shared/src/main/java/com/example/counter/shared_types/HttpRequest.java, examples/counter/Android/shared/src/main/java/com/example/counter/shared_types/TraitHelpers.java, examples/counter/cli/src/main.rs, examples/counter/iOS/CounterApp/ContentView.swift, examples/counter/shared/src/app.rs, examples/counter/web-nextjs/pages/index.tsx, examples/counter/web-yew/src/main.rs
Per title, exposes headers that are set on HTTP requests through to the shell, so that they can be sent out.
I've only updated the counter example; happy to do cat facts too if we want but it'd be a little more work (e.g. the shells currently only support HTTP GETs so would need bringing up to date).
=> Add support for HTTP request headers

crux_http/src/middleware/redirect.rs, crux_http/src/response/decode.rs, crux_http/src/response/response.rs, crux_http/src/response/response_async.rs
Just noticed these warnings in `crux_http` when running tests 😄 
warning: lint `missing_doc_code_examples` has been renamed to `rustdoc::missing_doc_code_examples`
There are still warnings that the lint is unstable, but now only half as many.
Was: warning: 12 warnings emitted
Now: warning: 6 warnings emitted
=> Rename rustdoc::missing_doc_code_examples lint

crux_http/src/client.rs, crux_http/src/protocol.rs, crux_http/tests/with_shell.rs, crux_http/tests/with_tester.rs
Based on [this Zulip discussion](https://crux-community.zulipchat.com/#narrow/stream/373912-general/topic/http-capability) I added a request body to the protocol HTTPRequest.
Could not simply update the `impl From<crate::Request> for HttpRequest` as I needed an `async` context therefore I created a designated `trait ProtocolRequestBuilder`.
Please review ...
=> feat(crux_http): added HTTPRequest::body to protocol.rs

.github/workflows/build.yaml
Add a trigger for the build workflow to also run on PRs (including forks). 
This should be safe to do, based on <https://securitylab.github.com/research/github-actions-preventing-pwn-requests/>
=> Run CI on PRs as well

crux_core/src/core/mod.rs
Core::resolve now returns a `Result<Vec<Effect>, ResolveError>`, so the errors don't just get swallowed.
I'm slightly on the fence about this – realistically, this is not an error that would happen occasionally at runtime, it's a design-time problem. There's also not much that can be done to handle it. It gets raised because the Shell is attempting to resolve a request that has already been resolved or never required resolving, and if it does happen, it is probably completely ok to ignore and carry on running (but needs investigating, because something is wrong with the effect handling).
This means the Shell code will be littered with somewhat unnecessary error handling. It might be better for Crux to just panic, like it does when used over the FFI bridge, and not bother the Shell code …
=> Surface resolve errors to Rust shells

crux_core/src/bridge/mod.rs, crux_core/src/bridge/registry.rs, crux_core/src/bridge/request_serde.rs, crux_core/src/capability/mod.rs, crux_core/src/core/effect.rs, crux_core/src/core/mod.rs, crux_core/src/core/request.rs, crux_core/src/core/resolve.rs, crux_core/src/lib.rs, crux_core/src/testing.rs, docs/src/SUMMARY.md, docs/src/getting_started/core.md, docs/src/getting_started/web_yew.md, docs/src/guide/core_api.md, docs/src/internals/effect.md, docs/src/internals/runtime.md
Updates the API docs and the book to reflect the recent changes to the Core API and splitting out the Bridge code.
While working on this, I've noticed there are a few types and methods which are `pub` and probably shouldn't be, and also a case of less than ideal error handling. I'll probably open another PR to tidy those bits up.
=> Update docs to cover the Core API changes

crux_core/src/capability/mod.rs
For capabilities which return a "signal" – an event with no payload, the Event type needs to be `Send`. This adds the trait bound to the `Capability` trait` trait.
=> Make event argument of Capability trait Send

examples/counter/Android/shared/build.gradle, examples/counter/README.md
Hi I played around a bit with crux and I was able to build the android example with these changes.
Maybe related to #82 altough I am not even sure what effect the toolchain file actually has?
The cli example also works. The others I have not tried yet. 
I thought I will provide this and maybe a nice discussion could emerge
=> enable windows users to build the android project

docs/src/getting_started/Android/android.md, examples/cat_facts/Android/shared/build.gradle, examples/counter/Android/shared/build.gradle, examples/simple_counter/Android/shared/build.gradle, templates/simple_counter/Android/shared/build.gradle
This PR improves documentation for Android and includes changes necessary to target all android devices supported by Mozilla's gradle plugin.
I have made changes to the android shared module's build.gradle in the template app; as well as, the relevant sample apps.
I have included instructions on the Android getting started covering the need to include the required rust toolchains and reflected the expected directory changes in the getting started guide.
=> Android improved documentation

crux_core/src/typegen.rs
When building the core app with an android target, java files are generated that we reference from kotlin to help facilitate our interaction with the core app. During this process, any types that were no longer being used were left in place. This PR updates the Java type generation helper clean up the shared types directory before generating the updated set of types.
=> Generated java types general housekeeping

Cargo.lock, crux_cli/Cargo.toml, crux_core/Cargo.toml, crux_macros/Cargo.toml, examples/bridge_echo/Cargo.lock, examples/bridge_echo/web-leptos/Cargo.toml, examples/bridge_echo/web-leptos/src/main.rs, examples/cat_facts/Cargo.lock, examples/cat_facts/shared/Cargo.toml, examples/cat_facts/web-yew/Cargo.toml, examples/counter/Cargo.lock, examples/counter/shared/Cargo.toml, examples/counter/tauri/src-tauri/Cargo.toml, examples/counter/web-leptos/Cargo.toml, examples/counter/web-leptos/src/main.rs, examples/counter/web-yew/Cargo.toml, examples/hello_world/Cargo.lock, examples/notes/Cargo.lock, examples/simple_counter/Cargo.lock, examples/simple_counter/web-leptos/Cargo.toml, examples/simple_counter/web-leptos/src/main.rs, examples/simple_counter/web-yew/Cargo.toml, templates/simple_counter/web-leptos/Cargo.toml, templates/simple_counter/web-leptos/src/main.rs, templates/simple_counter/web-yew/Cargo.toml
In Leptos 0.5.0, components no longer need context (`cx: Scope`), which simplifies our examples. This PR updates  our examples accordingly.
Also updates Yew to 0.21, Tauri to 1.5, `toml`, `thiserror`, and `insta` — all of which AFAICT have no breaking changes.
=> Leptos 0.5.0

crux_macros/src/capability.rs, docs/src/guide/capability_apis.md, examples/tap_to_pay/shared/src/capabilities/delay.rs
Fixes #147 by adding the Send trait to the generic type NewEv inside map_event function of the Capability macro.
In the tap_to_pay example, there is a Delay capability in which the same was done:
```rust
impl<Ev> Capability<Ev> for Delay<Ev> {
type Operation = DelayOperation;
type MappedSelf<MappedEv> = Delay<MappedEv>;
fn map_event<F, NewEvent>(&self, f: F) -> Self::MappedSelf<NewEvent>
where
F: Fn(NewEvent) -> Ev + Send + Sync + Copy + 'static,
Ev: 'static,
NewEvent: 'static + Send, // <------------- Send trait was added
{
Delay::new(self.context.map_event(f))
}
}
```
=> Added Send trait to NewEv generic type inside Capability derive macro

docs/src/getting_started/core.md
In the docs, in the section getting started, while following it I got slightly stuck on registering the app type (the Counter example just had a different name for the App (`App` instead of `Counter` in the getting started))
I'm trying to make the docs even more obvious to follow for the next person to read them.
=> Docs: Getting started: Add small precisions about registering app type

crux_core/Cargo.toml, examples/cat_facts/shared/Cargo.toml, examples/counter/Cargo.toml
`uuid` 1.7.0 has dropped the wasm-bindgen feature flag making it incompatible with previous versions (<= 1.6.1). 
The response from `uuid` maintainers:
> Thanks for pointing this out! The `wasm-bindgen` dependency was never meant to be public. It was only a Cargo limitation that made it so. Packages should instead use the js feature...
=> remove uuid unused wasm-bindgen feature flag

Cargo.lock, crux_core/src/capabilities/compose.rs, crux_core/src/capabilities/render.rs, crux_core/tests/capability_orchestration.rs, crux_http/tests/with_tester.rs, crux_kv/src/lib.rs, crux_kv/tests/kv_test.rs, crux_time/Cargo.toml, crux_time/src/lib.rs, crux_time/tests/time_test.rs, docs/src/guide/capabilities.md
Resolves #181 and #182.
Updates both KV and Time capbilities adding an async version of their API. I also switched the Time capability to use Chrono for the underlying representation - it supports timezones and serialization, so it was quite an easy choice. Open to suggestions for a better choice, if you think Chrono is too heavy a dependency for this. 
I also made `Render` capability `Clone` so it can be used along async composition (otherwise typical `Capabilities` can't be `Clone`).
=> Async KV and Time capability APIs

Cargo.lock, crux_http/Cargo.toml, crux_http/src/request.rs
The `crux_http` capability crate depended on the `http_types` feature `fs`, which does not compile for `wasm32-unknown-emscripten`. This PR removes that and the code that depended on it (which doesn't make sense inside a Crux core anyway).
=> remove http_types default features from crux_http

Cargo.lock, crux_http/CHANGELOG.md, crux_http/Cargo.toml
* `crux_http`: 0.4.6 -> 0.5.0 (⚠️ API breaking changes)
```
--- failure inherent_method_missing: pub method removed or renamed ---
Description:
A publicly-visible method or associated fn is no longer available under its prior name. It may have been renamed or removed entirely.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#item-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.28.0/src/lints/inherent_method_missing.ron
Failed in:
Request::body_file, previously in file /private/var/folders/vj/_19mcln57qz5j75lqqjtxc540000gn/T/.tmpDZPqgc/crux_http/src/request.rs:331
```
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- fix doc test deps
- remove http_types default features from crux_http
- More human readable change logs
</blockquote>
--- …
=> chore: release

Cargo.lock, crux_http/Cargo.toml
The published `http-types` crate uses 128bit `trace_id`, which doesn't compile for `wasm32-unknown-emscripten`.
See https://github.com/http-rs/http-types/pull/522
=> `crux_http` to use form of `http-types`

Cargo.lock, crux_http/Cargo.toml, crux_http/src/error.rs, crux_http/src/request_builder.rs, crux_http/src/response/response.rs
This should allow apps to handle HTTP errors better and provide special error handling for bad requests, unauthorized requests and other common situations that can be handled gracefully.
There are two changes
* A nicer error type which is easier to work with
* When using the event returning API, response status in the 4xx and 5xx range is considered an `Err` not an `Ok`
=> Better error handling for crux_http

crux_http/src/client.rs, crux_http/src/error.rs, crux_http/src/protocol.rs, crux_http/src/testing/fake_shell.rs, crux_http/tests/with_shell.rs, crux_http/tests/with_tester.rs
Introduce `HttpResult` to the shell protocol, to allow the shell to signal an error other than a HTTP error - currently these are IO and Timeout (there may be more to come).
=> crux_http: Allow non-HTTP errors to be represented by shell

Cargo.lock, crux_http/CHANGELOG.md, crux_http/Cargo.toml
New version of crux_http
- **The protocol between shell and core has changed. Core now expects a `HttpResult` rather than a `HttpResponse`**, see #204 for details
=> Release crux_http 0.7.0

crux_http/README.md, crux_http/src/error.rs, crux_http/src/lib.rs, crux_http/src/protocol.rs, crux_http/src/request_builder.rs, crux_http/src/response/response.rs, crux_http/src/response/response_async.rs, crux_http/tests/with_tester.rs
This avoids a type generation problem due to custom deserializer on `http::StatusCode`. 
The change also makes semantic sense - the shell-side of the capability should not be generating HTTP errors and JSON errors anyway, as that is done by the core side of it.
Even with this change, the type tracing is no longer able to find all the relevant types, and an additional line is required in the `build.rs` file in `shared_types`:
```rust
gen.register_type::<HttpError>()?;
```
=> crux_http: Restrict exported error variants

Cargo.lock, crux_http/CHANGELOG.md, crux_http/Cargo.toml
- Fixes a type generation problem with the newly exposed `HttpResult` and `HttpError`
- **Requires explicit tracing of crux_http::HttpError when using typegen**
=> Release crux_http 0.7.1

examples/counter/Cargo.lock, examples/counter/Cargo.toml, examples/counter/cli/src/core.rs, examples/counter/shared/src/app.rs, examples/counter/shared_types/build.rs, examples/counter/tauri/src-tauri/src/lib.rs, examples/counter/web-dioxus/src/core.rs, examples/counter/web-leptos/src/core.rs, examples/counter/web-yew/src/core.rs
This is work in progress for now, once we release #207 I'll bump to the newly rleased version of `crux_http` and merge
=> Update counter example to latest crux_core and crux_http.

Cargo.lock, crux_http/CHANGELOG.md, crux_http/Cargo.toml
- Updates the version of crux_http from 0.7.0 to 0.8.0
- Fixes a type generation problem with the newly exposed `HttpResult` and `HttpError`
=> chore: bump crux_http version to 0.8.0

examples/counter/Cargo.lock, examples/counter/Cargo.toml
Update Counter example to use newly published `crux_http` 0.8
=> chore: update crux_http dependency version to 0.8.0

docs/src/getting_started/Android/android.md, docs/src/getting_started/iOS/manual.md
I've added a few pointers for things I got stuck on or had to check when following the 'Getting Started' guide in the book.
Some of these will be helpful for Rust devs that aren't that familiar with app development, and others hopefully avoid getting stuck where there's sensitivity to exact naming or setup.
=> Docs: Suggestions from following the Getting Started guide

docs/src/guide/capability_apis.md
“it’s” is a contraction of “it is”.
=> docs: fix typo

crux_core/src/bridge/mod.rs, crux_core/src/bridge/registry.rs, crux_core/src/bridge/request_serde.rs, crux_core/src/capability/executor.rs, crux_core/src/capability/mod.rs, crux_core/src/capability/shell_request.rs, crux_core/src/core/effect.rs, crux_core/src/core/mod.rs, crux_core/src/core/resolve.rs, docs/src/SUMMARY.md, docs/src/guide/core_api.md, docs/src/internals/bridge.md, docs/src/internals/core_api.md, docs/src/internals/effect.md, docs/src/internals/runtime.md, docs/src/internals/serialization.md, docs/src/internals/uniffi.md
This is the beginning of the internals section of the docs.
I'm aiming to cover the capability runtime, Operations, Requests, and the serialisation in the bridge. The Effect derive macro and typegen are probably a separate docs PR.
=> Capability runtime documentation

Cargo.lock, crux_time/Cargo.toml, crux_time/src/duration.rs, crux_time/src/error.rs, crux_time/src/instant.rs, crux_time/src/lib.rs, crux_time/tests/time_test.rs
Updates `crux_time` capability to be more closely aligned with [`wasi-clocks`](https://github.com/WebAssembly/wasi-clocks/).
=> Instant and Duration subscriptions for `crux_time`

Cargo.lock, crux_macros/src/export.rs, docs/src/getting_started/core.md, examples/counter/Cargo.lock, examples/counter/shared/src/app.rs
Modifies the `Export` derive macro so that it respects the `name` set by the `effect` attribute for the `Effect` derive macro. This allows the following to work, creating `MyEffectFfi` to match the `MyEffect` type.
```rust
#[cfg_attr(feature = "typegen", derive(crux_core::macros::Export))]
#[derive(crux_core::macros::Effect)]
#[effect(name = "MyEffect", app = "NoteEditor")]
pub struct Capabilities {
timer: Timer<Event>,
render: Render<Event>,
pub_sub: PubSub<Event>,
key_value: KeyValue<Event>,
}
```
=> allow export derive macro to name effect

crux_kv/src/lib.rs, crux_kv/src/tests.rs, examples/cat_facts/Cargo.lock, examples/cat_facts/Cargo.toml, examples/cat_facts/shared/src/app.rs, examples/notes/Cargo.lock, examples/notes/Cargo.toml, examples/notes/shared/src/app.rs
This should make crux_kv a bit more idiomatic to use from inside the core. It no longer forces the user to deal with receiving a response to the wrong operation (which shouldn't happen anyway so is largely just boilerplate), and also works on standard `Results` rather than the FFI protocol result.
I've only changed the capability and its tests, haven't done examples in case people are violently opposed to this 🙂
=> Simplify app-facing API of crux_kv

crux_kv/src/error.rs, crux_kv/src/lib.rs, crux_kv/src/tests.rs, examples/cat_facts/cli/src/core.rs
Adds ability to list the keys in the store, providing a prefix (which can be an empty string), and a cursor for pagination (can be 0 to start from the beginning).
=> `crux_kv` capability list keys

Cargo.lock, Cargo.toml, crux_core/Cargo.toml, crux_platform/Cargo.toml, crux_time/Cargo.toml, examples/bridge_echo/Cargo.lock, examples/bridge_echo/cli/Cargo.toml, examples/cat_facts/Cargo.lock, examples/cat_facts/shared/Cargo.toml, examples/cat_facts/web-yew/Cargo.toml, examples/counter/Cargo.lock, examples/counter/cli/Cargo.toml, examples/counter/server/Cargo.lock, examples/counter/server/Cargo.toml, examples/counter/shared/Cargo.toml, examples/counter/web-dioxus/Cargo.toml, examples/counter/web-leptos/Cargo.toml, examples/counter/web-yew/Cargo.toml, examples/notes/Cargo.lock, examples/notes/shared/Cargo.toml
Should improve build times slightly, as I've used `cargo machete --fix` to remove unused deps
=> remove unused deps

crux_kv/README.md, crux_kv/src/lib.rs, crux_kv/src/tests.rs, crux_kv/src/value.rs, examples/cat_facts/Cargo.lock, examples/cat_facts/cli/src/core.rs, examples/cat_facts/shared/src/app.rs, examples/cat_facts/shared_types/build.rs, examples/notes/Cargo.lock, examples/notes/shared/src/app.rs, examples/notes/shared_types/build.rs, examples/notes/web-nextjs/src/app/core.ts
Introduces a `Value` enum, which is essentially a monnomorphised `Option<Vec<u8>>` to represent responses where the key does not exist (`get()`), or there was no previous value (`delete()` or `set()`). This type needs to exist as we can't (currently) get `Option<T>` over the FFI boundary. Note:  for now, `build.rs` for shared types libraries need to register this `Value` type explicitly as `serde_reflection` won't see it.
=> update API for crux_kv

crux_core/src/testing.rs, crux_core/tests/testing.rs
Convenient for creating non-default instances, e.g. in nested apps.
=> Add AppTester::new

.github/workflows/build.yaml, crux_http/src/protocol.rs, crux_kv/src/lib.rs, crux_kv/src/tests.rs
I realised that #253 can introduce a panic when handling non-ascii unicode character (see e.g. https://old.reddit.com/r/rust/comments/765n76/psa_caution_with_slicing_strings/). Here is the fix.
Also bumped the `pnpm` action to `v4`, as suggested in https://github.com/pnpm/pnpm/issues/6424.
=> Debug fmt handles unicode boundaries

crux_core/src/capabilities/compose.rs
Should help with #222. It doesn't fix it, but at least it adds the instruction for how to work around it.
=> Add documentation for effect(skip) to Compose

Cargo.lock, crux_http/Cargo.toml, examples/counter/Cargo.lock
Nightly clippy reported that the `crux_http` crate was using the feature `encoding`, which wasn't declared in `Cargo.toml`. This fixes that. But we should agree that this is what we want to do.
Note that the `decode_body` function changes to use `encoding_rs` for non-wasm targets, and `web-sys` for wasm targets.
=> http encoding feature

crux_core/src/capability/executor.rs, crux_core/src/core/mod.rs, crux_core/tests/capability_runtime.rs
This is a very subtle problem with the order of the fields of the `Core` type interacting with the async runtime when using channels (and possibly other coordination primitives).
The problem is this:
1. A capability creates a long running future with a loop
2. In order to communicate with this future it creates a channel, gives the receving end to the future and holds the sending end
3. The future gets to the point of receiving from the channel and suspends on `.await`. 
4. If the core is now dropped, then due to the original ordering of the fields, the executor is dropped first, causing the `task_sender` channel to close.
5. The `A::Capabilities` instance is dropped, dropping the capability instance, including the sending end of the channel
6. The channel's `Drop` implementation closes …
=> Fix a bug caused by drop order of the `Core` struct

Cargo.lock, crux_http/Cargo.toml, crux_http/src/protocol.rs
This marks the `body` field in `crux_http`'s `HttpRequest` and `HttpResponse` types with the `#[serde(with = "serde_bytes")]` annotation. This is effectively a hint for Serde to serialize it as a byte array instead of a vector of numbers.
See also: https://docs.rs/serde_bytes/latest/serde_bytes/
I could put this behind a feature flag, but given that the annotation is ignored on formats that don't support byte arrays, I think there might be no need. This also means it will remain a vector of numbers for JSON encoding, since JSON has no functionality for binary encoding. The annotation is mainly relevant for formats such as MessagePack and CBOR.
For formats that work with fixed-size vectors, such as bincode, I don't think there will be any difference either, although I have not tested this.
=> Mark HTTP body with serde_bytes

crux_core/src/testing.rs
Hello there,
I was trying to test an app where app instance communicate over a WebSocket. To do so I had the receiving party waiting in an async task for a message and then have the app resolve the event. To do so I required to send it to another thread, hence requiring Send.
Hence these small changes.
Thoughts.
PS: thanks for this crate, love it !
=> AppTester Send

crux_core/src/testing.rs, crux_http/tests/with_tester.rs, crux_kv/src/tests.rs, crux_macros/src/effect.rs, crux_time/tests/time_test.rs
Here are a couple of ideas for how to make the tests less boilerplate-y. They are mostly minor helper methods but together I think they make the tests significantly more readable while also being more robust.
The most controversial parts are likely to be
* `fn expect_<effect>` to go along with `fn into_<effect>`
- only saves a few keystrokes vs `into_<effect>().unwrap()` but I think it reads better
* Adding `#[must_use]` to the `Update` struct. This is to force the user to make it clear that they haven't forgotten that more stuff might happen in 'real life'
- If we expect it to be empty, use `.assert_empty()`, otherwise write `let _update = ...` to silence the warning
I have ported a couple of tests to the new methods to illustrate how it might change how tests look. If we are happy with …
=> Add helper methods to `Update` to remove test boilerplate

crux_http/Cargo.toml, crux_kv/Cargo.toml, crux_time/Cargo.toml
This was an oversight on previously released capabilities `crux_http`, `crux_kv` and `crux_time`, which could not be built for the `typegen` feature, because its dependency on `crux-core/typegen` was not specified.
It probably didn't end up affecting common usage because `crux-core` (with `typegen` enabled) is usually specified as a build dependency in the `shared_types` crates, but for correctness all features should be buildable.
=> capability typegen feature must depend on core typegen

examples/bridge_echo/Cargo.lock, examples/bridge_echo/shared/src/app.rs, examples/cat_facts/Cargo.lock, examples/cat_facts/shared/src/app.rs, examples/cat_facts/shared/src/app/platform.rs, examples/counter/Cargo.lock, examples/counter/shared/src/app.rs, examples/hello_world/Cargo.lock, examples/notes/Cargo.lock, examples/notes/shared/src/app.rs, examples/simple_counter/Cargo.lock, examples/simple_counter/shared/src/app.rs, examples/tap_to_pay/shared/src/app.rs
Update tests in examples to use the return value from `app.update()`.
This is temporary  and will be succeeded by https://github.com/redbadger/crux/pull/280
=> must_use on app.update()

crux_time/src/lib.rs, crux_time/tests/time_test.rs
Hi! I was playing around with the `time` capability and realised there's no way to clear the pending timer.  This PR adds this possibility. 
This PR adds `TimeId` field for relevant requests/responses of `crux_time` capability. Since we know the id of the timer we are able to clear it using the new time request: `TimeRequest::Clear {id: TimeId}`. Once core notifies the shell (`notify_shell` since we don't expect any response to this particular request) with this effect, the shell should fire the initially set timer sooner with a `TimeResponse::Cleared` instead of `TimeResponse::InstantArrived`/`TimeResponse::DurationElapsed`.
I'm open to any suggestions, I'm also aware that this is a breaking change, maybe you guys see a non-breaking solution to this? Otherwise I will just create a custom …
=> feat(crux_time): cancellable timer

crux_core/src/capability/mod.rs, crux_core/src/capability/shell_request.rs, crux_core/src/capability/shell_stream.rs, crux_core/src/testing.rs, crux_core/tests/capability_orchestration.rs, crux_http/tests/with_tester.rs, crux_kv/src/tests.rs, crux_platform/src/lib.rs, crux_time/tests/time_test.rs, docs/src/guide/testing.md, doctest_support/src/lib.rs, examples/bridge_echo/Cargo.toml, examples/bridge_echo/shared/src/app.rs, examples/cat_facts/Cargo.lock, examples/cat_facts/Cargo.toml, examples/cat_facts/shared/Cargo.toml, examples/cat_facts/shared/src/app.rs, examples/cat_facts/shared/src/app/platform.rs, examples/counter/Cargo.lock, examples/counter/Cargo.toml, examples/counter/shared/Cargo.toml, examples/counter/shared/src/app.rs, examples/hello_world/Cargo.lock, examples/hello_world/Cargo.toml, examples/hello_world/shared/src/app.rs, examples/notes/Cargo.lock, examples/notes/Cargo.toml, examples/notes/shared/src/app.rs, examples/tap_to_pay/Cargo.toml
- Adds a `Clone` bound on  the `Operation` trait so that we can examine the operation and still resolve its owning request later on — this is a breaking change.
- Adds a `take_effects` method on `Update` to allow you to take effects off the Update that match the predicate
- Adds a `take_effects_partitioned_by` method on `Update` to allow you to take effects off the Update that match the predicate and also the remaining effects that don't match
- Updates all the crates' tests and the examples' tests to make use of these new testing helpers (and the ones already released in `crux_core` 0.9.0 and 0.9.1)
- Note: the examples now reference local crates, but I'll change that after the helpers are published
=> `Clone` bound on `Operation` (breaking) and test helper methods

crux_core/src/core/mod.rs
Under certain specific circumstances, it was possible cause a deadlock due to not dropping a lock on the model.
I haven't yet worked out exactly why/when this happens (or rather, why it doesn't happen always/often), but here's the fix.
=> Drop model to avoid deadlock

examples/bridge_echo/iOS/BridgePerf.xcodeproj/project.pbxproj, examples/bridge_echo/iOS/BridgePerf/ContentView.swift, examples/bridge_echo/iOS/BridgePerf/SparklineView.swift, examples/bridge_echo/shared/src/app.rs
This pull request updates the `examples/bridge_echo` project, specifically improving the iOS application and the shared Rust library by adding a sparkline view and implementing stop/start logic, as mentioned in https://github.com/redbadger/crux/pull/136#issuecomment-1700793055 by @charypar 
As depicted in the graph below, the number of calls will decrease over time:
=> feat(examples): add sparkline and stop/start for bridge_echo on iOS

Cargo.lock, crux_core/CHANGELOG.md, crux_core/Cargo.toml, crux_http/CHANGELOG.md, crux_http/Cargo.toml, crux_kv/CHANGELOG.md, crux_kv/Cargo.toml, crux_macros/CHANGELOG.md, crux_macros/Cargo.toml, crux_platform/CHANGELOG.md, crux_platform/Cargo.toml, crux_time/CHANGELOG.md, crux_time/Cargo.toml
The API has been improved, which is a breaking change. More details in these PR descriptions:
- [crux_time API improvement](https://github.com/redbadger/crux/pull/284)
- [Cancelling a timer also aborts the cancelled task](https://github.com/redbadger/crux/pull/292)
=> `crux-time` release

examples/bridge_echo/README.md
Fix typo in crux/examples/bridge_echo/README.md
=> Fix typo in crux/examples/bridge_echo/README.md

crux_http/src/request_builder.rs, crux_http/tests/with_tester.rs
For the http capability... Following the same pattern as constructing other body types (body as bytes plus specific content-type header), this little change adds the ability to create a body for posting forms. Any name-value pair structure that can be serialised and url-encoded can be used as the data type. The doc comment example uses a HashMap for instance.
=> http capability: add body_form to http request builder

crux_core/src/bridge/mod.rs, crux_core/src/capabilities/compose.rs, crux_core/src/capabilities/render.rs, crux_core/src/capability/mod.rs, crux_core/src/command/RFC.md, crux_core/src/command/mod.rs, crux_core/src/core/mod.rs, crux_core/src/lib.rs, crux_core/src/testing.rs, crux_core/src/typegen.rs, crux_core/tests/capability_orchestration.rs, crux_core/tests/capability_runtime.rs, crux_core/tests/json_bridge.rs, crux_core/tests/testing.rs, crux_core/tests/typegen.rs, crux_http/tests/with_shell.rs, crux_http/tests/with_tester.rs, crux_kv/src/tests.rs, crux_macros/src/effect.rs, crux_macros/src/lib.rs, crux_platform/tests/platform_test.rs, crux_time/tests/time_test.rs
This makes the necessary changes to make Commands usable with `Core` and `AppTester`.
It makes a fair few breaking changes to type signatures, but all quite mechanical and simple. I'll follow this up with a migration guide which people can follow.
=> Command support in Core

crux_core/src/command/builder.rs, crux_core/src/command/mod.rs, crux_core/src/command/tests/combinators.rs, crux_core/src/lib.rs, crux_kv/src/command.rs, crux_kv/src/lib.rs
This adds a new module called`command` to `crux_kv` which provides KV command builder constructors.
Because KV presents a different interface to the core than the protocol it has with the shell, it needs to do post-processing_ on the results. I took the opportunity to add `.map` to `RequestBuilder` and `StreamBuilder`. I also made some missed out parts of this API public in `crux_core`. 
This should put is in a good place to tackle more complicated capabilities.
**note**: this will require a patch release of `crux_core` and therefore a patch release of `crux_kv` (and potentially all capabilities - haven't thought about that too hard)
=> Command support in crux_kv and tweaks and fixes to the Command API to enable the capability migration

examples/counter/shared/src/app.rs, examples/counter/shared/src/capabilities/sse.rs
Updates the `ServerSentEvents` capability in the `counter` example to use the new `Command` API. 
Note that during the migration phase, this capability has to also be compatible with the old API so that `#[derive(Effect)]` can generate the relevant `Effect` enum variant. As we move past the migration, capabilities will become vanilla structs that have no special meaning in Crux and effectively just become `Command` generators. At this point we can simplify this capability, removing the `CapabilityContext`.
=> update ServerSentEvents capability in examples to command

docs/src/getting_started/core.md, docs/src/guide/hello_world.md, examples/counter/shared/src/app.rs
Once the migration to the new command API is complete, the app's update function will no longer require capabilities as a parameter. This PR updates the counter example's update function to defer to our _own_ update function, which matches the signature that the App trait will soon require.
We can now test the app directly, rather than relying on the `AppTester` (which will be deprecated).
=> Update tests in the counter example to not use AppTester

crux_core/src/command/mod.rs
These helpers could perhaps help cut down on some boilerplate
=> Add from/into helpers to Command

crux_core/src/command/mod.rs
This is a very easy trap to fall into and we should help people avoid it.
=> Commands must be used

Cargo.lock, crux_time/Cargo.toml, crux_time/src/command.rs, crux_time/src/lib.rs
As part of this, I've revised how the cancellation works so that idea of IDs doesn't leak into the app.
=> Command interface for crux_time

crux_core/src/command/mod.rs, crux_core/src/command/tests/async_effects.rs, crux_core/src/command/tests/combinators.rs
Previous implementation of Command::and would create a cons-list shaped structure when folding over a list of commands with `.and`. This change makes it effectively equivalent to creating the folded list with `::all` by wrapping the `other` command in `.and` to be hosted on `self`s pair of channels, and spawning it in `self`.
As a side effect, this also adds a `spawn` API on a mutable command instance. Being pretty much equivalent with `Command::new` in what it can do, I think this can be public, but I could be talked out of that :).
There are potentially other similar optimisations in other places which wrap existing commands in new commands rather than merging them.
=> Avoid creating deep recursive calls with Command::and

Cargo.lock, crux_core/src/bridge/mod.rs, crux_core/src/command/builder.rs, crux_core/src/command/mod.rs, crux_core/src/command/tests/async_effects.rs, crux_core/src/command/tests/combinators.rs, crux_core/src/lib.rs, crux_http/src/command.rs, doctest_support/Cargo.toml, doctest_support/src/lib.rs
Improves API docs for the `crux_core::command` module, giving examples of some of the different ways in which `Command`s can be used.
=> crux_core command docs wip

docs/src/getting_started/core.md
* This PR attempts to improve the crux getting started documentation here: https://redbadger.github.io/crux/getting_started/core.html
* The minor change being made is to update the referenced `crux_core` version to be `0.12.0`, since that was needed to compile the rest of the example code.
=> chore: update core.md to reference crux 0.12.0

docs/src/getting_started/iOS/manual.md, examples/bridge_echo/iOS/BridgePerf.xcodeproj/project.pbxproj, examples/bridge_echo/iOS/project.yml, examples/cat_facts/iOS/CatFacts.xcodeproj/project.pbxproj, examples/cat_facts/iOS/project.yml, examples/counter/iOS/CounterApp.xcodeproj/project.pbxproj, examples/counter/iOS/project.yml, examples/notes/iOS/Notes.xcodeproj/project.pbxproj, examples/notes/iOS/project.yml, examples/simple_counter/iOS/SimpleCounter.xcodeproj/project.pbxproj, examples/simple_counter/iOS/project.yml, examples/tap_to_pay/iOS/TapToPay.xcodeproj/project.pbxproj, examples/tap_to_pay/iOS/project.yml, templates/simple_counter/iOS/CounterApp.xcodeproj/project.pbxproj, templates/simple_counter/iOS/project.yml
The actual path of uniffi-bindgen's build artifact is `"${BUILD_DIR}/Debug/uniffi-bindgen"`, not `"${BUILD_DIR}/debug/uniffi-bindgen"`.
The latter only happens to work on case-insensitive volumes and with "Build configuration: Debug", afaict.
To reproduce (on `master`):
1. Open "TapToPay" iOS project
2. Clean the project's build folder via "Main Menu" > "Product" > "Clean Build Folder…" (or via <kbd>command</kbd> <kbd>shift</kbd> <kbd>K</kbd>)
3. Build the project via "Main Menu" > "Product" > "Build" (or via <kbd>command</kbd> <kbd>B</kbd>)
The build should succeed. As expected.
Now repeat the steps, but before building the project (step 3) change the project's build configuration from "Debug" to "Release" via "Main Menu" > "Product" > "Scheme" > "Edit Scheme…" (or via <kbd>command</kbd> …
=> Fix path of Xcode-generated “uniffi-bindgen” executable artifact

crux_time/src/command.rs, crux_time/tests/cancellation.rs, docs/src/guide/testing.md, examples/bridge_echo/Cargo.lock, examples/cat_facts/Cargo.lock, examples/cat_facts/shared/src/app.rs, examples/counter/Cargo.lock, examples/hello_world/Cargo.lock, examples/notes/Cargo.lock, examples/notes/shared/src/app.rs, examples/simple_counter/Cargo.lock
=> `crux_time` API w.r.t `TimerId`

crux_core/src/command/context.rs, crux_time/src/command.rs
This one is quite hard to explain.
`ShellRequest` is constructed on top of a `ShellStream`, and we use [`StreamFuture` from futures](https://docs.rs/futures/latest/futures/prelude/stream/struct.StreamFuture.html) to represent this. 
The peculiar thing about `ShellRequest` is that it panics if it's polled again after it returned Ready. Logically, this shouldn't happen in our case - the stream is actually a future, it will resolve at most once. The problem is the "at most" part. If it never resolves and the shell side of it (the `Request`) is cleaned up, the channel underneath closes and the stream terminates without ever producing a value. 
In this case `ShellRequest` returns `Pending` when polled, and is immdiately discovered by the check for wakers - there are no more wakers and the task …
=> Allow ShellRequest future to be polled many times after the request is dropped.

crux_core/src/typegen.rs, crux_macros/src/effect.rs, crux_macros/src/export.rs, examples/cat_facts/shared/src/app.rs, examples/cat_facts/shared/src/app/platform.rs, examples/cat_facts/shared_types/build.rs, examples/counter/shared_types/build.rs, examples/simple_counter/shared_types/build.rs
This PR moves the `Export` trait implementation from `Capabilities` to `Effect` so that we can call `Effect::register_types` from `register_app`.
=> Effect registration when using `effect!`

crux_core/src/capabilities/compose.rs, crux_core/src/lib.rs, crux_macros/src/effect.rs, docs/src/getting_started/core.md, examples/simple_counter/shared/src/app.rs
Some very minor tweaks to the `effect!` macro (that includes a better error message), and an update to the `getting started` guide in the book.
=> improve effect macro and docs

crux_core/src/command/executor.rs, crux_core/src/command/tests/executor.rs, crux_core/src/command/tests/mod.rs
This fixes a subtle bug which can drop longer-running tasks to aggressively, when they return `Pending` from poll, but have already marked themselves ready and dropped the waker.
To handle the exception, I had to slightly rework how we process the ready queue, adding an explicit buffer which can be scanned for the id of a task which is suspended with no wakers, to see if it's also ready.
=> Fix an executor bug that evicts tasks which wake themselves immediately and drop the waker

crux_core/src/capabilities/render.rs, crux_core/src/command/builder.rs, crux_core/src/command/mod.rs, crux_core/src/command/tests/basic_effects.rs, crux_core/tests/json_bridge.rs, crux_core/tests/testing.rs, crux_http/tests/capability_with_shell.rs, crux_http/tests/command_with_shell.rs, examples/notes/shared/src/app.rs, examples/notes/shared/src/capabilities/pub_sub.rs
**Breaking Change**: Command API changed — `notify_shell` now returns `NotificationBuilder`, instead of `Command`
Adds `NotificationBuilder` which has symmetry with `RequestBuilder` and `StreamBuilder`, but without continuations. This is useful where you need to notify the shell from an async context. There is also now a `From` implementation to convert the builder into a command. 
Updated the `Render` capability accordingly. 
Note: it is recommended to implement capabilities in terms of builders rather than commands, so that they can be used in both sync and async contexts. However, `render::render()` currently returns a command, so we kept it that way to minimise breakages, and instead introduced `render::render_builder()` to return a builder.
=> NotificationBuilder

docs/src/SUMMARY.md, docs/src/guide/android-apk-shrink.md, examples/bridge_echo/Android/shared/build.gradle, examples/cat_facts/Android/shared/build.gradle, examples/counter/Android/shared/build.gradle, examples/simple_counter/Android/shared/build.gradle, templates/simple_counter/Android/shared/build.gradle
This is kinda 3 issues in 1, happy to break them up if wanted
1. Slight tweak in when type and bind gen happen
- Fairly confident this has no negative side effects
2. Added workaround for the gradle plugin
- I'm a bit unsure if we want to add workarounds to the examples or not 
3. Started documenting shrinking the APK for android builds
- Probably want to reword most of it to fit, i also haven't got round to building the docs myself so i may have linked it wrong in summery
=> Android build fixups / documentation

docs/book.toml
See https://github.com/szabgab/public-mdbooks/issues/10
=> remove the unused and deprecated `multilingual` field from `book.toml`

crux_core/src/testing.rs
This allow to show the caller location in in panic messages. In practice it means that panic messages will point the the user test code instead of crux testing code.
=> crux_core/testing: Add track_caller to resolve_to_event_then_update

crux_macros/src/effect.rs
This allow to convert the effect enum into the underlying request in a generic way. This is mainly usefull for testing and allow to write functions that convert into an operation type without knowing the concrete Effect type.
```rust
fn expect_http_effect(effect: impl TryInto<crux_core::Request<HttpRequest>>) {
...
}
```
=> crux_macros: Implement TryFrom for effect

Cargo.lock, crux_http/Cargo.toml, crux_http/src/error.rs, crux_http/src/protocol.rs
Introduces query on protocol::HttpRequestBuilder
The `crux_http` library has a query method to create query strings on `command::RequestBuilder`, but when writing tests for a crux core application
we would do something like 
```rust
let mut request = cmd.effects().next().unwrap().expect_http();
let expected_url = format!(
"{}?lat={}&lon={}&appid={}",
WEATHER_URL, lat_lng.0, lat_lng.1, API_KEY
);
// Before the changes in this PR
assert_eq!(&request.operation, &HttpRequest::get(expected_url).build());
// After the changes in the PR expose a query method
assert_eq!(
&request.operation, // If we had query strings, the URL would already have it appended
&HttpRequest::get(API_URL)
// .query doesn't exist here as this is Protocol::HttpRequestBuilder. So we would have to format a string as an …
```
=> add .query() method to protocol::HttpRequestBuilder

crux_core/src/typegen.rs
Hi, if you don't mind a change like this I would be happy to extend in onto other Typegen errors.
=> Make Typegen errors more informative

Cargo.lock, crux_cli/Cargo.toml, crux_cli/codegen.fish, crux_cli/src/codegen/formatter.rs, crux_cli/src/codegen/mod.rs, examples/counter-next/Cargo.lock, xtask/Cargo.toml
- Skip built-in Rust crates (std, core, alloc, proc_macro, test) that don't have manifests
- Add support for f32 and f64 primitive types in codegen formatter
- Fixes 'unknown crate alloc/std' and 'need to implement primitive f32/f64' errors
=> fix(crux_cli): Handle built-in crates and add f32/f64 primitive support

crux_core/src/bridge/request_serde.rs, crux_core/src/core/mod.rs, crux_core/src/core/request.rs, crux_core/src/core/resolve.rs, crux_core/src/lib.rs, crux_core/src/testing.rs, crux_time/tests/cancellation.rs, examples/counter-next/shared/src/app.rs, examples/counter/Cargo.lock, examples/counter/cli/Cargo.toml, examples/counter/shared/src/app.rs, examples/counter/tauri/src-tauri/Cargo.toml
fixes: #374
Following conversation on #369, change the `resolve` API on `Core` to accept a `RequestHandle`, which is a new name for what's currently called `Resolve`. 
For backwards compatibility, we update the API to be generic over an impl of `Resolvable` trait implemented on both `Request<Op>` and `RequestHandle<Out>`.
=> Request handle

examples/counter-next/shared/src/app.rs, examples/counter-next/shared/src/capabilities/sse.rs
Modifies the `sse` capability in `counter-next` example to remove support for deprecated capabilities.
=> feat(counter_next): remove legacy boilerplate from sse capability

crux_core/Cargo.toml
Hi,
by default crux_core was pulling uniffi which is only required at build step, not at compile step... and is very slow to compile on cold builds (sometimes hot ones as well).
This allows the consumer of the lib to feature gate uniffi and turn it off when just compiling the core
=> turn uniffi optional

crux_http/Cargo.toml
Hi, I stumbled upon this one while analyzing slow compilation on my hand and noticed web-sys was compiled for no reason. This can be circumvented on the consumer side by conditionally enabling the feature upon the target being wasm but it would be better to have it default.
=> turn web-sys crate conditional on wasm32 arch in crux_http

examples/counter-next/Cargo.lock, examples/counter-next/shared/src/app.rs
The problem was a very basic state management bug – even in the case of the random number being 0, the model was changed to a pending state.
=> Fix "I'm feeling lucky button" in counter-next

Cargo.lock, Cargo.toml, crux_core/Cargo.toml, crux_core/src/type_generation/facet.rs, crux_core/src/type_generation/serde.rs, crux_core/typegen_extensions/swift/requests.swift, crux_core/typegen_extensions/typescript/serde/binaryDeserializer.ts, crux_macros/Cargo.toml, examples/.gitignore, examples/counter-next/Android/app/src/main/java/com/crux/example/counter/sse.kt, examples/counter-next/Android/gradle/libs.versions.toml, examples/counter-next/Android/gradle/wrapper/gradle-wrapper.properties, examples/counter-next/Cargo.lock, examples/counter-next/iOS/CounterApp/sse.swift, examples/counter-next/shared/Cargo.toml, examples/counter-next/shared/src/capabilities/sse.rs, examples/counter-next/shared_types/build.rs, examples/counter-next/web-remix/app/sse.ts, examples/weather/Cargo.toml
Use `facet_generate` v0.4, which has namespace support for creation of specified modules in Swift, Kotlin and TypeScript. Updated `counter-next` example to put the types from the `ServerSentEvents` capability into their own namespace and tested for iOS, Android and NextJS.
=> feat(crux_core): facet typegen with module support

crux_core/src/bridge/mod.rs, crux_core/src/bridge/registry.rs, crux_core/src/capability/mod.rs, crux_core/src/core/effect.rs, crux_core/src/core/mod.rs, crux_core/src/lib.rs, crux_core/src/middleware/bridge.rs, crux_core/src/middleware/mod.rs, crux_core/tests/json_bridge.rs, crux_core/tests/middleware.rs, crux_core/tests/testing.rs, crux_macros/src/effect/macro_impl.rs, crux_macros/src/effect/tests.rs, crux_macros/src/effect_derive.rs, examples/counter-next/shared/src/ffi.rs, examples/hello_world/Cargo.lock, examples/hello_world/shared/Cargo.toml, examples/hello_world/shared/src/app.rs
The `Serialize`/`Deserialize` bounds are only really required when working with FFI and type generation, but are currently on the `App` trait and the `Effect` type for all uses.
This moves them up to the two bridge implementations and splits the effect derive macros to allow use without serialization, if no typegen is requested.
=> Relax Serialize bound when not using Bridge.

crux_core/src/capability/mod.rs, crux_core/src/type_generation/facet.rs, crux_macros/src/effect/macro_impl.rs, crux_macros/src/effect/tests.rs, examples/counter-next/shared_types/build.rs
Note: applies to facet-based typegen only.
Replace `TypeGen` (whose `ensure_registry()` would panic if misused) with `TypeRegistry` and `CodeGenerator` to ensure a type safe transition between the 2 stages. Also provides a nicer api:
```rust
TypeRegistry::new()
.register_app::<App>()
.register_type::<OtherType>()
.build()
.swift(config)?;
```
=> TypeRegistry and CodeGenerator for typesafe transition between stages

Cargo.lock, Cargo.toml, crux_cli/Cargo.toml, crux_cli/src/bindgen/mod.rs, crux_core/Cargo.toml, crux_core/src/type_generation/facet.rs, crux_core/typegen_extensions/kotlin/Requests.kt, crux_http/Cargo.toml, crux_kv/Cargo.toml, crux_time/Cargo.toml, examples/bridge_echo/Cargo.lock, examples/cat_facts/Cargo.lock, examples/counter-next/Android/app/src/main/java/com/crux/example/counter/Core.kt, examples/counter-next/Android/app/src/main/java/com/crux/example/counter/MainActivity.kt, examples/counter-next/Android/app/src/main/java/com/crux/example/counter/http.kt, examples/counter-next/Android/app/src/main/java/com/crux/example/counter/sse.kt, examples/counter-next/Android/shared/build.gradle, examples/counter-next/Cargo.lock, examples/counter-next/Cargo.toml, examples/counter-next/shared/Cargo.toml, examples/counter-next/shared/src/app.rs, examples/counter-next/shared/src/bin/codegen.rs, examples/counter-next/web-leptos/Cargo.toml, examples/counter/Cargo.lock, examples/hello_world/Cargo.lock, examples/notes/Cargo.lock, examples/simple_counter/Cargo.lock, examples/weather/Cargo.lock
Add support for the new Kotlin type generation in [`facet_generate`](https://github.com/redbadger/facet-generate), and update the `counter-next` example to use Kotlin typegen instead of Java in the Android shell.
Note: also back-revs some deps to be equal to that of crux_core 0.16, so that we don't accidentally break users when they update to 0.16.1
=> Support for Kotlin typegen

crux_core/src/middleware/effect_handling.rs, crux_core/tests/middleware.rs, examples/counter-next/Cargo.lock, examples/counter-next/shared/src/middleware.rs
Fixes #428, by adjusting the effect callback in middleware to take request handle by mutable borrow, instead of value.
=> [Breaking] Fix effect middleware to support stream requests and multipl resolutions
