.gitignore, README.md, docs/local-execution.md, docs/new-project-android.md, docs/new-project-core-rust.md, docs/new-project-ios.md, docs/new-project-yew-web.md, docs/new-project.md
I've rewritten the README to make it more _"non-expert friendly"_
Also, the instructions for running the demo locally, and creating new projects have been split off into separate files
=> Expand readme

README.md, crux_core/README.md, crux_core/src/capability.rs, crux_core/src/future.rs, crux_core/src/lib.rs, crux_core/src/render.rs, crux_core/src/steps.rs, crux_core/src/testing.rs, crux_core/src/typegen.rs, crux_http/src/lib.rs, crux_http/tests/with_shell.rs, crux_kv/src/lib.rs, crux_kv/tests/kv_test.rs, crux_platform/tests/platform_test.rs, crux_time/src/lib.rs, crux_time/tests/time_test.rs
Update rustdoc for all the public APIs
=> Rustdoc for version 0.2

examples/counter/Android/.idea/codeStyles/Project.xml, examples/counter/Android/.idea/codeStyles/codeStyleConfig.xml, examples/counter/README.md
Whilst following the `counter` example, I encountered a few problems.
These are now listed along with their fixes
=> Small corrections and clarifications to README

Cargo.lock, README.md, crux_core/Cargo.toml, crux_core/README.md, crux_core/src/capability.rs, crux_core/src/typegen.rs, crux_http/Cargo.toml, crux_kv/Cargo.toml, crux_platform/Cargo.toml, crux_time/Cargo.toml, examples/cat_facts/Cargo.lock, examples/cat_facts/shared/Cargo.toml, examples/counter/Cargo.lock, examples/counter/server/Cargo.toml, examples/counter/shared/Cargo.toml, examples/counter/shared_types/Cargo.toml, examples/hello_world/Cargo.lock, examples/hello_world/shared/Cargo.toml, examples/hello_world/shared_types/Cargo.toml, examples/notes/Cargo.lock, examples/notes/shared/Cargo.toml
bumps
- `crux_core` to `0.3`
- `crux_http` to `0,2`
- other capabilities to `0.1`
=> prep for 0.3 release

docs/src/guide/hello_world.md
=> Corrected typo in guide.

examples/cat_facts/README.md, examples/counter/README.md, examples/hello_world/README.md
=> update readme files for pnpm installation

examples/hello_world/shared/src/counter.rs, examples/hello_world/shared/src/hello_world.rs, examples/hello_world/shared/src/lib.rs, examples/hello_world/shared_types/build.rs
@charypar here's an update to your `direct-core-api` branch that gets the hello_world example and tests building. Might save you some busy work :)
=> Update hello_world for Bridge

examples/cat_facts/Android/.idea/gradle.xml, examples/cat_facts/Android/.idea/misc.xml, examples/cat_facts/Android/app/src/main/AndroidManifest.xml, examples/cat_facts/Android/build.gradle, examples/cat_facts/Android/shared/build.gradle, examples/counter/Android/.idea/gradle.xml, examples/counter/Android/.idea/misc.xml, examples/counter/Android/app/src/main/AndroidManifest.xml, examples/counter/Android/build.gradle, examples/counter/Android/shared/build.gradle, examples/hello_world/Android/.idea/gradle.xml, examples/hello_world/Android/.idea/misc.xml, examples/hello_world/Android/app/src/main/AndroidManifest.xml, examples/hello_world/Android/build.gradle, examples/hello_world/Android/shared/build.gradle
update android studio to Giraffe, and associated SDKs
=> android updates

crux_core/src/typegen.rs
Additional commit for #155 
closes #155 
(apologies pushed to the wrong place).
=> Typegen error messages

crux_http/src/request_builder.rs, crux_http/src/response/response_async.rs, crux_http/tests/with_tester.rs
=> Add async API to crux_http

docs/src/guide/capabilities.md
I've tested this inside the integration test, but didn't commit that change. Can do if you'd like.
=> Update capability orchestration docs to use working code

crux_http/src/error.rs
=> add display implementation for crux_http::error::Error

docs/src/getting_started/core.md
Fixes #210 
Some of the links in the getting started guide for the shared (and shared types) libraries were pointing to the `counter` example instead of the `simple_counter` example, which was confusing. 
Also the workspace `Cargo.toml` were incorrect if you are following along as it had workspace members that don't exist yet.
=> Update book getting started guide to fix links and cargo toml examples

crux_time/README.md
I just heard of this project on YouTube. What a great idea! I am studying it now
=> fix a link error in README

docs/src/internals/runtime.md
@charypar nice job on these docs! I think they are clear and comprehensive. Here are a few suggestions for clarification, from an end-user perspective.
=> Clarifications to capability runtime docs

crux_kv/src/lib.rs
Relax a couple more callback bounds in the newly-updated `crux_kv`
=> relax callback bounds in crux_kv

Cargo.lock, crux_core/CHANGELOG.md, crux_core/Cargo.toml, crux_http/CHANGELOG.md, crux_http/Cargo.toml, crux_kv/CHANGELOG.md, crux_kv/Cargo.toml, crux_macros/CHANGELOG.md, crux_macros/Cargo.toml, crux_platform/CHANGELOG.md, crux_platform/Cargo.toml, crux_time/CHANGELOG.md, crux_time/Cargo.toml, templates/simple_counter/shared_types/Cargo.toml
=> crux_core 0.8.0-rc.1

crux_http/src/protocol.rs, crux_kv/src/lib.rs, crux_kv/src/tests.rs
=> Better HttpRequest and KeyValueOperation Debug format

Cargo.lock, crux_kv/Cargo.toml, crux_kv/src/lib.rs, crux_kv/src/value.rs
Similar to  #267 , but for `crux_kv`
=> use serde_bytes in crux_kv

Cargo.toml, crux_core/src/capability/channel.rs, crux_core/src/capability/executor.rs, crux_kv/src/tests.rs, crux_macros/src/lib.rs
Also need to bump MSRV since we use LazyLock in crux_time
=> Fix clippy warnings

examples/cat_facts/Cargo.lock, examples/cat_facts/Cargo.toml, examples/cat_facts/shared/src/app.rs
this depends on #301 being released, but moves CatFacts to use the changes there-in
=> [Blocked] Migrate cat_facts to new crux_kv. 

crux_http/src/client.rs
This should help with some debugging
=> crux_http: change an unwrap to an expect

crux_core/src/testing.rs, crux_macros/src/effect.rs
This gives better feedback when the asserts fail
=> Add `#[track_caller]` to test helpers

crux_time/src/command.rs
Implements `PartialEq` and `Eq` for `TimerHandle`
=> crux_time: add PartialEq and Eq to TimerHandle

crux_time/src/command.rs
And also never emit the immediately cancelled ones.
Needs merging #331 first.
=> Make time effects deterministic

crux_macros/src/effect.rs
This prevented custom names for the `Effect` type when using the new derive macro
=> Fix Effect macro bug

crux_core/src/command/mod.rs, crux_core/src/command/tests/combinators.rs
This aligns the Command api with {Request,Stream}Builder and allow to chain commands from inside the task function allowing to use capabilities that don't return values (for example an analytics capability) and use Commands as return values.
=> feat(crux_core): Add into_future to Command

Cargo.lock, crux_cli/Cargo.toml, crux_core/Cargo.toml, crux_core/src/type_generation/facet.rs, examples/counter-next/Cargo.lock, examples/counter-next/web-remix/app/core.ts
Updates the TypeScript type generation to use the new features in [`facet-generate`](https://github.com/redbadger/facet-generate) v0.9.0
=> feat(counter-next): update facet typegen for typescript
